CREATE TABLE IF NOT EXISTS mpa_ratings(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(65) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(65) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
  	description varchar(200),
  	release_date timestamp,
  	duration integer,
  	mpa_id integer REFERENCES mpa_ratings(id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    genre_id integer REFERENCES genres(id),
    film_id integer REFERENCES films(id),
    PRIMARY KEY (genre_id,film_id )
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  	email varchar(255) NOT NULL,
  	login varchar(255),
  	name varchar(255),
  	birthday timestamp
);

CREATE TABLE IF NOT EXISTS users_relations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  	primary_user_id integer REFERENCES users(id),
  	secondary_user_id integer REFERENCES users(id),
  	relation_accepted boolean
);

CREATE TABLE IF NOT EXISTS likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  	film_id integer REFERENCES films(id),
  	user_id integer REFERENCES users(id)
);